### ISSUE TITLE
When will the code of the thesis "Unify Graph Learning with Text: Unleashing LLM Potentials for Session Search" be published

### ISSUE THREAD

**Issue by QQQQQQBY** [wsh-rucgl/SGR#1]
When will the code of the thesis "Unify Graph Learning with Text: Unleashing LLM Potentials for Session Search" be published？

**Comment by ericshwu** [comment]
We have shared a copy of the messy code with you via email and will sort out the code as soon as possible. If you have any other questions, feel free to contact me.

**Comment by ericshwu** [comment]
We have updated the organized code. If you have any other questions, feel free to submit a new issue.
